### ISSUE TITLE
Merging Features from Modified Script?

### ISSUE THREAD

**Issue by ClashSAN** [Animator-Anon/Animator#1]
https://pastebin.com/QZc3dnPx
Didn't fully uncover the available features from the modified addition. Would it be worthwhile to add anything from this or is it outdated?

**Comment by Animator-Anon** [comment]
That looks like an old version of the script enhanced by someone, I haven't had a play with it yet, but will check it out. You can probably do most of it with keyframes.

**Comment by ClashSAN** [comment]
alright, good to know
