### ISSUE TITLE
Question/Issue: Animation "starts" over?

### ISSUE THREAD

**Issue by jet3004** [Animator-Anon/Animator#10]
<img width="735" alt="test" src="https://user-images.githubusercontent.com/106498013/195740387-5b770f76-5568-4afb-acaa-f88aa04ea2ba.png">
<img width="488" alt="Screen_Shot_2022-10-13_at_6 15 51_PM" src="https://user-images.githubusercontent.com/106498013/195740389-d3a085c5-dc09-42a6-91cf-4d004f049187.png">

How do prevent the ‘animation’ from starting over and having these ‘blank’ spots in the middle of the compositions? I’m sure this is trivial but it’s not clicking. I'm trying to create a 'seamless' endless loop, like I've seen others do.

"Apply color correction to imgzimg results to match original colors" is set in Settings.

Thank you.

**Comment by Animator-Anon** [comment]
It might be a symptom of the keyframe and image staying the same for too long. I have been experimenting with ways to inject noise into the picture to help it start creating new things, but nothing good has come from this so far. best thing is to keep things moving and keyframes changing i think.

**Comment by jet3004** [comment]
> It might be a symptom of the keyframe and image staying the same for too long. I have been experimenting with ways to inject noise into the picture to help it start creating new things, but nothing good has come from this so far. best thing is to keep things moving and keyframes changing i think.

Ah. I actually read that maybe my non-matching aspect ratio caused that and I should just stick with 512x 512, too, because that's what the model was trained on?

**Comment by Animator-Anon** [comment]
The SD model was trained on 512x512 yeah, and it works best at that resolution. If you increase it, you can end up with Cronenberg style body horror.
Mostly running the same image back in img2img causes visual problems. Try it without the animation script selected.

**Comment by Animator-Anon** [comment]
Is this still an issue? Can you give me a prompt to try? If not I'll close.

**Comment by jet3004** [comment]
Yes, it is still an issue...Most all renders I do are 'ruined' by this happening at one or multiple points. No specific prompt really and its's still happening with 512x512, I can't figure it out. Can you give me another random 'working' animation prompt?

**Comment by Animator-Anon** [comment]
I can probably give you some prompts that work, but that might not expose your issue. Do you have a set of prompts you can give me that burn a hole in the image and I can see if I can reproduce?

**Comment by Animator-Anon** [comment]
Try this:
Positive Template:
highway, sunshine, high detail, photo realistic, dramatic lighting, octane render

Keyframes:
0| denoise | 0.4

0| transform | 0.75 | -150| 0 | 0
0| prompt | Volkswagen, beetle, new, car | 

2| transform | 1.0 | 0 | 0 | 0
2| prompt | Volkswagen, beetle, new, car | 

4 | prompt | transformer, autobot, humanoid, standing up, robot,  on road | Volkswagen, beetle, new, car

8 | transform | 1.0 | 100 | 0 | 0
8 | prompt | transformer, autobot, humanoid, standing up, robot,  (running left:1.2), on road | Volkswagen, beetle, new, car

**Comment by VirtuallyOrange** [comment]
This is most likely an issue with novelai and its VAE. You need to run at full precision.
Try doing the exact same settings, but put —no-half-vae in the argument (webui-user.bat).
This happens over time, but nobody really could explain to me why.

**Comment by jet3004** [comment]
> 

<img width="1456" alt="Screen Shot 2022-10-22 at 11 14 12 AM" src="https://user-images.githubusercontent.com/106498013/197356593-8c5df415-e614-4378-8064-62f291f7b98c.png">

Hey, thanks so much! I was able to test this with the exact settings and it's still 'starting over' with each prompt, I guess is the best way to put it? Is that intended or are people achieving the 'seamless' in a different way? Can your new 'march seed' option help? Appreciate it.

**Comment by jet3004** [comment]
> This is most likely an issue with novelai and its VAE. You need to run at full precision.
> Try doing the exact same settings, but put —no-half-vae in the argument (webui-user.bat).
> This happens over time, but nobody really could explain to me why.

Thanks, just saw your comment after my reply...I will try this!

**Comment by Animator-Anon** [comment]
Is this fixed?

**Comment by jet3004** [comment]
> Is this fixed?

No, sorry, I had tested a few times the last few days with "—no-half-vae" and still ran into the 1 or 2 frames darkening THEN completely black frame, here and there, every few dozen or hundred frames. And this is now just trying with one video keyframe like "1| source | video | /Users/jet/Downloads/test.mp4" to keep it simple. The results, without the random dropped frames, are otherwise amazing. It's too random on when exactly it happens but consistently does for me.

**Comment by Animator-Anon** [comment]
I don't know what the problem is, or what I can do to help.
Is it reproducible? I.e. if it happens, can you run the same prompts, starting picture etc though again and get the same result?

It seems to be a problem with running a picture through img2img for too long. when you process a video, a frame is grabbed, processed and saved to disk. No feeding the result back in.
