### ISSUE TITLE
[Feature Request] Angle shift. 

### ISSUE THREAD

**Issue by ethanborden** [Animator-Anon/Animator#12]
Fantastic script!

Would love the ability to rotate that canvas.
Tho understand that would introduce a border issue.

**Comment by Animator-Anon** [comment]
It certainly is possible using the opencv2 transform function, it just fills in the edge with repeated edge pixels. I have experimented with it, and went back to my own function when trying to introduce noise. I'll add it to my transform function next update.

**Comment by Animator-Anon** [comment]
Check out v2 script. Note the new prompt format.
