### ISSUE TITLE
Feature request: keyframe and fps unlock

### ISSUE THREAD

**Issue by Aceftwspades** [Animator-Anon/Animator#13]
I understand that the keyframe is currently tied to fps, and when you want to make a change at x second in your animation that would be your number. Correct me if I’m wrong but does that not limit us to making changes only on 1 second intervals? In the interest of making music videos and syncing the animation tightly I’m curious if there’s a way to uncouple them or to make changes at specific frames rather than on the fps limiter

**Comment by Animator-Anon** [comment]
Yeah the script just renders a series of images. The fps, at the basic level, is just a parameter passed to ffmpeg so it creates the resulting video at the specified frame rate. The script starts at frame one, and works through to the end frame (time * fps). Each frame, a check is made to see if any keyframes exist, and those changes are made. The keyframe time, and fps are floating point numbers, so you should be able to target a specific frame with some math. Maybe use a spreadsheet to help story boarding.
For example, setting a keyframe at 2.54s, with a framerate of 33.3267FPS, will lead the changes to be applied at frame: 2.54 * 33.3267 = 84.649818, rounded down to frame 84.
Does that help?

**Comment by Aceftwspades** [comment]
Oh cool I wasnt quite sure if I could use partial numbers! My other idea was to just set it at 1 fps and fix it later with ffmpeg 🤣 amazing work so far I’ve been having a lot of fun with your script. I’m hoping I can make a web app to help me auto generate keyframe changes within your format to control the “camera” parameters since the keyframe generators I’ve found don’t play nice with your format.

**Comment by Animator-Anon** [comment]
Is there a standard format you want supported? With the v2 script, I can add many new commands..

**Comment by Aceftwspades** [comment]
https://www.chigozie.co.uk/audio-keyframe-generator/ 

This site generates a couple different formats, since  your keyframe data is all kind of one block versus what I’m able to output here. If perhaps there were separate input fields for each type of transformation    This site generates data for each frame, rather than the frame x fps, so I’m not sure how compatible they really are. So I want to make the functionality of that site but compatible with your script. With the ability to control all the variables.
