### ISSUE TITLE
potential img2img embossing fix

### ISSUE THREAD

**Issue by jeffgyf** [Animator-Anon/Animator#14]
When you say img2img embossing do you mean the image with some patterns like this? If so I may have worked a fix for this and would like to make a pull request.
![20221014135638_00099](https://user-images.githubusercontent.com/16674327/195976021-d6111c23-9898-4ee2-a637-3f364bcfae18.png)

**Comment by Animator-Anon** [comment]
![20221015180623_00000](https://user-images.githubusercontent.com/114563845/195976740-77b991d4-f62f-49fd-927f-83c565cafdf9.png)
![20221015180623_00299](https://user-images.githubusercontent.com/114563845/195976751-d7002509-43aa-4342-8aa8-c1d8d0c6d2ef.png)
Yeah this effect, where the image is static with a low denoise value. I am building a v2 script, so if you submit a pull request I might roll the changes into that.

**Comment by jeffgyf** [comment]
Sure, see https://github.com/Animator-Anon/Animator/pull/15, feel free to do whatever you'd like.

**Comment by Animator-Anon** [comment]
Ah I see what's going on now, a prompt weighting feature I didn't know about it. I am rolling it into my v2 script, which handles the keyframes a bit differently.

**Comment by Animator-Anon** [comment]
Oh and thanks for the contribution! Before I forget.
