### ISSUE TITLE
images get darker and less defined as rendering for long videos. 

### ISSUE THREAD

**Issue by wedgeewoo** [Animator-Anon/Animator#16]
for some reason i cannot get the right setting to prevent the image to get darker and become more "blobby" for longer generated videos. And way to work around this?

**Comment by Animator-Anon** [comment]
Yes it's a side effect of running over the same image. The new v2 script I am working on will have frame interpolation, which seems to help in this area. I recommend giving it a go and seeing how things work out. Watch this space.

**Comment by wedgeewoo** [comment]
Hey I gave the v2 a shot and it looks like it doesnt get darker but it starts to get "dotted" for some reason. 
1 frame
![20221015212524_00000](https://user-images.githubusercontent.com/112199050/196018438-52d410a0-4ad5-4704-97db-b269110442d7.png)
107 frame
![20221015212524_00107](https://user-images.githubusercontent.com/112199050/196018443-acee2429-1ef9-47b9-9dc7-9051cd1a606b.png)
 Any work around for that?

**Comment by Animator-Anon** [comment]
As far as I know, this is what happens when you don't change the picture enough. Low denoise value and not moving.
If you do a slow pan or zoom, that would help. If you don't want to creatively, you may have to repeat the frame.
Picture looks awesome though!

**Comment by Animator-Anon** [comment]
Here is an example of the effect when reducing denoising, static picture.
Key frames:
0 | denoise | 0.5
0 | prompt | cat | 
0 | set_text | t1 | Denoise: 0.5 | 100 | 400 | 255 | 255 | 255 | 0 | 0 | 0 | arial.ttf | 60
 
4 | denoise | 0.4
4 | set_text | t1 | Denoise: 0.4 | 100 | 400 | 255 | 255 | 255 | 0 | 0 | 0 | arial.ttf | 60
 
8 | denoise | 0.3
8 | set_text | t1 | Denoise: 0.3 | 100 | 400 | 255 | 255 | 255 | 0 | 0 | 0 | arial.ttf | 60
 
12 | denoise | 0.2
12| set_text | t1 | Denoise: 0.2 | 100 | 400 | 255 | 255 | 255 | 0 | 0 | 0 | arial.ttf | 60

16 | denoise | 0.1
16 | set_text | t1 | Denoise: 0.1 | 100 | 400 | 255 | 255 | 255 | 0 | 0 | 0 | arial.ttf | 60


[20221016163620.webm](https://user-images.githubusercontent.com/114563845/196022057-3b707cbf-f7bd-4238-bb53-7f204f74f035.webm)

**Comment by Animator-Anon** [comment]
Here is a pan. Looks like it doesn't help a great deal. Someone smarter than me will have to figure it out.
[20221016165045.webm](https://user-images.githubusercontent.com/114563845/196022604-6212c995-37e8-4b0a-a70b-42ec304265fd.webm)

**Comment by Animator-Anon** [comment]
I see this is happening, might be more what you need.
https://github.com/deforum-art/deforum-for-automatic1111-webui
