### ISSUE TITLE
Trying out the new prop feature. 

### ISSUE THREAD

**Issue by Aceftwspades** [Animator-Anon/Animator#18]
I can’t seem to get a prop to work, it doesn’t throw an error, just nothing seems to happen. I have the prop path set in the field and the prop name set to what seems correct. I do have some questions about the x and y pos if trying to center the prop, I have saved as png at 512x512 for simplicity would the x and y pos be 0 or something like 256? 
I’m excited to try the new commands

**Comment by Animator-Anon** [comment]
Yes you are right, I broke it when adding new features and didn't go back and test. Try it now.
