### ISSUE TITLE
I have an error and I don't know why :/

### ISSUE THREAD

**Issue by zeoo01** [Animator-Anon/Animator#19]
I think I'm typing something wrong?

"Iteration 1/150:   0% 0/9 [00:00<?, ?it/s]
Iteration 1/150:  11% 1/9 [00:00<00:01,  4.59it/s]
Iteration 1/150:  22% 2/9 [00:00<00:01,  5.07it/s]
Iteration 1/150:  33% 3/9 [00:00<00:01,  5.23it/s]
Iteration 1/150:  44% 4/9 [00:00<00:00,  5.29it/s]
Iteration 1/150:  56% 5/9 [00:00<00:00,  5.34it/s]
Iteration 1/150:  67% 6/9 [00:01<00:00,  5.35it/s]
Iteration 1/150:  78% 7/9 [00:01<00:00,  5.35it/s]
Iteration 1/150:  89% 8/9 [00:01<00:00,  5.38it/s]
Iteration 1/150: 100% 9/9 [00:01<00:00,  5.31it/s]
Error completing request
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x512 at 0x7F64D2461F90>, None, None, None, 0, 20, 0, 4, 1, False, False, 1, 1, 10, 0.75, 3994915769.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 1, '<p style="margin-bottom:0.75em">Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Keyframe Format: <br>Time (s) | Desnoise | Zoom (/s) | X Shift (pix/s) | Y shift (pix/s) | Positive Prompts | Negative Prompts | Seed</p>', '10.0', '15', True, False, False, '1.0', 'a detailed realistic painting of lion, by Hyperrealistic, greg rutkowski and xiang duan,', '((masked)), cropped, [[faceless]], horrible, [[mutated]] [[[deformed]]], ugly [[blurry]] mutation bad anatomy disfigured', '0 | 0.4 | 1.0 | 0 | 0 | red | | |\n3 | 0.4 | 1.0 | 0 | 0 | blue | | |\n6 | 0.4 | 1.0 | 0 | 0 | green | | |\n9 | 0.4 | 1.0 | 0 | 0 | gray | | |', 0.4, '0', '0', False, False, 0.1, 0.5, '<p style="margin-bottom:0.75em">Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Initial Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Props</p>', '<p style="margin-bottom:0.75em">Supported Keyframes:<br>time_s | prompt | positive_prompts | negative_prompts<br>time_s | transform | zoom | x_shift | y_shift | rotation<br>time_s | seed | new_seed_int<br>time_s | denoise | denoise_value<br>time_s | prop | prop_filename | x_pos | y_pos | scale | rotation<br>time_s | set_text | textblock_name | text_prompt | x | y | fore_R | fore_G | fore_B | back_R | back_G | back_B | font_name | font_size<br>time_s | clear_text | textblock_name<br>time_s | prop | prop_name | prop_filename | x pos | y pos | scale | rotation<br>time_s | set_stamp | stamp_name | stamp_filename | x pos | y pos | scale | rotation<br>time_s | clear_stamp | stamp_name<br>time_s | col_set<br>time_s | col_clear<br>time_s | model | model</p>', '10.0', '15', False, False, False, '1.0', 'a detailed realistic painting of lion, by Hyperrealistic, greg rutkowski and xiang duan,', '((masked)), cropped, [[faceless]], horrible, [[mutated]] [[[deformed]]], ugly [[blurry]] mutation bad anatomy disfigured',, '1 | | red | |\n3 | | blue | |\n6 | | green | |\n9 | | gray | |', 0.4, '0', '0', '0', False, False, 0, 0.5, '/content/drive/MyDrive/img/', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, None, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/sd/stable-diffusion-webui/modules/ui.py", line 212, in f
    res = list(func(*args, **kwargs))
  File "/content/sd/stable-diffusion-webui/webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "/content/sd/stable-diffusion-webui/modules/img2img.py", line 124, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/sd/stable-diffusion-webui/modules/scripts.py", line 162, in run
    processed = script.run(p, *script_args)
  File "/content/sd/stable-diffusion-webui/scripts/animation.py", line 338, in run
    processed = processing.process_images(p)
  File "/content/sd/stable-diffusion-webui/modules/processing.py", line 444, in process_images
    image = apply_color_correction(p.color_corrections[i], image)
  File "/content/sd/stable-diffusion-webui/modules/processing.py", line 43, in apply_color_correction
    channel_axis=2
TypeError: match_histograms() got an unexpected keyword argument 'channel_axis'"

**Comment by Animator-Anon** [comment]
Looks like you are trying to use the old prompt style, it has changed in v2.
0 | 0.4 | 1.0 | 0 | 0 | red | | |
3 | 0.4 | 1.0 | 0 | 0 | blue | | |
6 | 0.4 | 1.0 | 0 | 0 | green | | |
9 | 0.4 | 1.0 | 0 | 0 | gray | | |

Looks like the prompt is changing, so you can use these:
0 | prompt | red |
3 | prompt | blue |
6 | prompt | green |
9 | prompt | gray |

Put the templates in as before. See what happens. are you dragging an image into the img2img box? It needs one to start off. Try running img2img without my script enabled, make sure that works first.

**Comment by zeoo01** [comment]
> Looks like you are trying to use the old prompt style, it has changed in v2. 0 | 0.4 | 1.0 | 0 | 0 | red | | | 3 | 0.4 | 1.0 | 0 | 0 | blue | | | 6 | 0.4 | 1.0 | 0 | 0 | green | | | 9 | 0.4 | 1.0 | 0 | 0 | gray | | |
> 
> Looks like the prompt is changing, so you can use these: 0 | prompt | red | 3 | prompt | blue | 6 | prompt | green | 9 | prompt | gray |
> 
> Put the templates in as before. See what happens. are you dragging an image into the img2img box? It needs one to start off. Try running img2img without my script enabled, make sure that works first.

It fails again, Im using your method, I dont know what happen :( Img2img it works well, maybe its because Im using a colab with Xformers?
https://colab.research.google.com/drive/1ldtKemsf1jCfoEd5onTOeXJtp1Kkcqze#scrollTo=R-xAdMA5wxXd
(dont judge me, this colab its cool not only for furry hahahah)

**Comment by Animator-Anon** [comment]
I don't know anything about running on google colab, sorry.  I might not be able to help you.

So you just need one of the scripts in the custom script folder, and it will be available in the img2img page. You also need ffmpeg installed on the path if you want to create videos. You could probably deselect every video option and copy the frames down to your local machine, modify the bat file and run it there.

It looks like this error is occurring when trying to apply colour corrections. Can you run img2img with colour corrections enabled? Without my script? With the supplied loopback script? Have you tried different starting pictures? Send one from txt2img?
I don't want to log into your furry haven with my google account lol.

**Comment by Animator-Anon** [comment]
Did you figure this out?

**Comment by zeoo01** [comment]
> Did you figure this out?

yeah, it was a problem of the colab, I just change the colab and now it works

**Comment by Animator-Anon** [comment]
Too easy, thanks!
