### ISSUE TITLE
support for windows paths

### ISSUE THREAD

**Issue by daouid** [Animator-Anon/Animator#2]
"[WinError 3] The system cannot find the path specified: 'outputs/img2img-images\\20221001122145'"

**Comment by cibernicola** [comment]
Windows 10 user here, it works fine.
Are you filling all parameters?

**Comment by daouid** [comment]
ok thanks, I gave it another try, worked now, to resolve I had to set in the setting page an output directory, under:
"Output directory for images; if empty, defaults to three directories below"

**Comment by Animator-Anon** [comment]
Yes I also use Windows 10. Hope it works under Linux!
