### ISSUE TITLE
Use image sequence as input?

### ISSUE THREAD

**Issue by bhickenbottom** [Animator-Anon/Animator#20]
Would it be possible to use an image sequence as the input, like running an existing video's frames through SD?

**Comment by Animator-Anon** [comment]
It would be possible yes. Probably wouldn't be that hard to do, just load each frame, set as the init image, set the rest of the parameters, process it, dump the result to disk.
Not really in the scope of this project to do that., Be worth checking if something doesn't already exist, like this:
https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py

**Comment by Animator-Anon** [comment]
Did you find a solution?

**Comment by Animator-Anon** [comment]
I'll look into it, it will take a bit of a rewrite. Until the deforum extension adds keyframe support, that is!

**Comment by diramazioni** [comment]
What you mean by  keyframe support? You can already specify keyframe/prompt like in your script, problem is that is a scene cut, it doesn't blend in with the previous keyframes, 
With deforum is possible to do prompt interpolation and it works somewhat, (still experimenting)

**Comment by Animator-Anon** [comment]
Yes I see now, I haven't tried to use the extension. Looks like a bunch of progress has been made.
Anyway I have added support for videos as a frame source, use the source keyframe.
Image sequences still to be figured out.

**Comment by Animator-Anon** [comment]
Completed in v5.

**Comment by diramazioni** [comment]
Hello, thanks for looking into it, can you complete it with an example usage?
I see in the prompts is now possible to specify
`time_s | source | video, images, img2img | path` 
Can you explain the parameters?

**Comment by Animator-Anon** [comment]
To img2img a video, use this keyframe:
0 | source | video | c:/videos/cat.webm

It would make sense to set the FPS to match the video FPS, so other prompts you add happen at predictable times.

to img2img a folder full of images:
0 | source | images | c:/videos/*.png

The time doesn't matter, but it needs to be a number, so 0 works.
