### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Flonixcorn** [Animator-Anon/Animator#22]
Error completing request████████████████████████▉                                  | 1350/3000 [03:00<02:59,  9.17it/s]
Arguments: (0, 'highway, sunshine, high detail, photo realistic, dramatic lighting, octane render', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x512 at 0x2CB1E565DE0>, None, None, None, 0, 20, 0, 4, 0, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 3, '<p style="margin-bottom:0.75em">Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Keyframe Format: <br>Time (s) | Desnoise | Zoom (/s) | X Shift (pix/s) | Y shift (pix/s) | Positive Prompts | Negative Prompts | Seed</p>', '10.0', '15', False, False, True, '1.0', '', '', '', 0.4, '0', '0', False, False, 0.1, 0.5, '<p style="margin-bottom:0.75em">Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Initial Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Props</p>', '<p style="margin-bottom:0.75em">Supported Keyframes:<br>time_s | prompt | positive_prompts | negative_prompts<br>time_s | transform | zoom | x_shift | y_shift | rotation<br>time_s | seed | new_seed_int<br>time_s | denoise | denoise_value<br>time_s | prop | prop_filename | x_pos | y_pos | scale | rotation<br>time_s | set_text | textblock_name | text_prompt | x | y | fore_R | fore_G | fore_B | back_R | back_G | back_B | font_name | font_size<br>time_s | clear_text | textblock_name<br>time_s | prop | prop_name | prop_filename | x pos | y pos | scale | rotation<br>time_s | set_stamp | stamp_name | stamp_filename | x pos | y pos | scale | rotation<br>time_s | clear_stamp | stamp_name<br>time_s | col_set<br>time_s | col_clear<br>time_s | model | DefaultSD_sd-standard-model, DefaultSD_sd-v1-4-full-ema, DefaultSD_sd-v1-5-inpainting, DefaultSD_v1-5-pruned, DefaultSD_v1-5-pruned-emaonly, NovelAIModels_final-pruned, Styles_Anime_waifu-diffusion-model-epoch07-float16, Styles_Anime_wd-v1-2-full-ema, Styles_Anime_wd-v1-3-float16, Styles_Midjourney_a photo in the style of MJ%, Styles_Midjourney_midjourney style, Styles_Others_Hiten girl_anime_8k_wallpaper_4k, Styles_Robot_Use _nousr robot_ as keyword_robo-diffusion-v1, Styles_Trinart_trinart2_step115000, custom models_AI overlord $KAI, custom models_a photo of a $KS, custom models_a photo of a $KS  2, custom models_a photo of a sks man, custom models_a photo of beautiful sks woman, custom models_sks young blonde man</p>', '10.0', '15', False, False, True, '1.0', '', '', '', 0.4, '0', '0', '0', False, False, 0.1, 0.5, '', '<p style="margin-bottom:0.75em">Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Initial Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Props</p>', '<p style="margin-bottom:0.75em">Supported Keyframes:<br>time_s | prompt | positive_prompts | negative_prompts<br>time_s | transform | zoom | x_shift | y_shift | rotation<br>time_s | seed | new_seed_int | delta<br>time_s | subseed | new_subseed_int | delta<br>time_s | denoise | denoise_value<br>time_s | prop | prop_filename | x_pos | y_pos | scale | rotation<br>time_s | set_text | textblock_name | text_prompt | x | y | w | h | fore_color | back_color | font_name<br>time_s | clear_text | textblock_name<br>time_s | prop | prop_name | prop_filename | x pos | y pos | scale | rotation<br>time_s | set_stamp | stamp_name | stamp_filename | x pos | y pos | scale | rotation<br>time_s | clear_stamp | stamp_name<br>time_s | col_set<br>time_s | col_clear<br>time_s | model | DefaultSD_sd-standard-model, DefaultSD_sd-v1-4-full-ema, DefaultSD_sd-v1-5-inpainting, DefaultSD_v1-5-pruned, DefaultSD_v1-5-pruned-emaonly, NovelAIModels_final-pruned, Styles_Anime_waifu-diffusion-model-epoch07-float16, Styles_Anime_wd-v1-2-full-ema, Styles_Anime_wd-v1-3-float16, Styles_Midjourney_a photo in the style of MJ%, Styles_Midjourney_midjourney style, Styles_Others_Hiten girl_anime_8k_wallpaper_4k, Styles_Robot_Use _nousr robot_ as keyword_robo-diffusion-v1, Styles_Trinart_trinart2_step115000, custom models_AI overlord $KAI, custom models_a photo of a $KS, custom models_a photo of a $KS  2, custom models_a photo of a sks man, custom models_a photo of beautiful sks woman, custom models_sks young blonde man</p>', '10', '15', False, True, False, '1', 'highway, sunshine, high detail, photo realistic, dramatic lighting, octane render', '', '0| denoise | 0.4\n\n0| transform | 0.75 | -150| 0 | 0\n0| prompt | Volkswagen, beetle, new, car |\n\n2| transform | 1.0 | 0 | 0 | 0\n2| prompt | Volkswagen, beetle, new, car |\n\n4 | prompt | transformer, autobot, humanoid, standing up, robot, on road | Volkswagen, beetle, new, car\n\n8 | transform | 1.0 | 100 | 0 | 0\n8 | prompt | transformer, autobot, humanoid, standing up, robot, (running left:1.2), on road | Volkswagen, beetle, new, car', 0.4, '0', '0', '0', False, False, 0.1, 0.5, '', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 4, 0.09, True, 1, 0, 7, False, False, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, None, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, False, 4.0, '', 10.0, True, False, True, 30.0, False, True, 10.0, True, 30.0, True, '', '', 100, 0, 0, True, '<div class="gr-block gr-box relative w-full overflow-hidden border-solid border border-gray-200 gr-panel"><p>If you like my work, please consider showing your support on <strong><a href="https://patreon.com/thereforegames" target="_blank">Patreon</a></strong>. Thank you! &#10084;</p></div>', '', '', 24, '24', 'hh:mm:ss', 'hh:mm:ss', False, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "X:\AI\SUPER SD 2.0 Dependencies\stable-diffusion-webui\modules\ui.py", line 212, in f
    res = list(func(*args, **kwargs))
  File "X:\AI\SUPER SD 2.0 Dependencies\stable-diffusion-webui\webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "X:\AI\SUPER SD 2.0 Dependencies\stable-diffusion-webui\modules\img2img.py", line 124, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "X:\AI\SUPER SD 2.0 Dependencies\stable-diffusion-webui\modules\scripts.py", line 173, in run
    processed = script.run(p, *script_args)
  File "X:\AI\SUPER SD 2.0 Dependencies\stable-diffusion-webui\scripts\animator_v3.py", line 634, in run
    make_mp4(outpath, outfilename, fps, vid_mp4 & (not state.interrupted), False)
  File "X:\AI\SUPER SD 2.0 Dependencies\stable-diffusion-webui\scripts\animator_v3.py", line 214, in make_mp4
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\Flonixcorn\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Flonixcorn\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Animator-Anon** [comment]
Do you have ffmpeg installed on path?
