### ISSUE TITLE
[Feature Request] "ease in" & "ease out" feature for keyframes

### ISSUE THREAD

**Issue by VirtuallyOrange** [Animator-Anon/Animator#23]
I don't understand enough, if it is doable or not:
Is it possible to add options to ease into our out of keyframes?
Right now, everything is linear, meaning transformations (zoom, shift, rotation) start "all of a sudden" and keep going with the same value.

![the-key](https://user-images.githubusercontent.com/114165880/197338697-5e5e16bd-6fa3-4c4b-ad38-b6f06af1367e.gif)

How likely can something akin to the keyframe options in after effects be implemented?

**Comment by Animator-Anon** [comment]
Yes, the groundwork has been laid. There is linear interpolation in v4. Check the .csv file in the output folder to see how the values change. 
High forms require more data-points, so there would have to be say 4 transform keyframes to make polynomial interpolation possible. I can add a check and enable this method. That would most likely apply over the whole animation though. Having separate interpolation methods per keyframe would take a bit more work.

**Comment by Animator-Anon** [comment]
Did you get the result you were after?
