### ISSUE TITLE
[Bug Report] animation_v4.py ignores "Pixel Shift"

### ISSUE THREAD

**Issue by VirtuallyOrange** [Animator-Anon/Animator#24]
When filling out X and Y pixel shifts, it seems like the newest animation_v4.py ignores whatever is writting in there (rotation and zoom will still be respected though).

Steps to reproduce:
1.) Put animation_v4.py into the script folder
3.) in the webui, drag & drop an image into the img2img tab
2.) select script "animation_v4.py" from dropdown menu
3.) fill out the zoom, shift and rotation fields

When generating now, observe how rotation and zoom will still be respected, yet shift (x and y) will be ignored.
(in "animator_v3.py" shift x & y was still respected)

**Comment by Animator-Anon** [comment]
Yes I broke the pre and post processing order of things, should be better now.
