### ISSUE TITLE
Seed Consistency and Frame manipulation?

### ISSUE THREAD

**Issue by 3oxis-Prim3** [Animator-Anon/Animator#25]
Hi, first and foremost: THANK YOU FOR THIS!!
My questions: Is there any way to maintain the same seed throughout the animation generation?
Secondly, how do you add keyframes so you can enter a new prompt?
Thanks for your time.
Cheers.

**Comment by Animator-Anon** [comment]
It's generally a bad idea to keep the same seed unless the image is transforming allot, you will get a bunch of visual artefacts.
However you still can, add a seed keyframes with the same seed number to keep it the same.:
0 | seed | 12345
4 | seed | 12345

Just write all the keyframes in the box at the bottom, there is no add button and another list somewhere:
0 | prompt | cat |
2 | prompt | dog |
4 | prompt | pangolin |

**Comment by 3oxis-Prim3** [comment]
Thanks Bro
