### ISSUE TITLE
V2 Function to add noise missing in V4 and V5 Can we have it back?

### ISSUE THREAD

**Issue by electroblep** [Animator-Anon/Animator#29]
I liked in V2 that you could "add noise" and there was a slider to adjust it. It really helped me have consistancy between images by keeping the denoise lower, but by slowly adding noise back, it kept it from degrading over time, as well as other additional benefits. I don't see this option in V4 or V5. If it is still there, please let me know where. If not, please put the option back in. Thank you!

**Comment by Animator-Anon** [comment]
My bad, I thought it was trash and that no one used it!
I'll put it back and add a keyframe to set the noise strength, so you can change it on the fly.

**Comment by Animator-Anon** [comment]
Also did you mean the old salt and pepper style pixel noise from the first implementation, or the coloured circles from the second implementation? If you have suggestions for a better method, let me know.

**Comment by electroblep** [comment]
> My bad, I thought it was trash and that no one used it! I'll put it back and add a keyframe to set the noise strength, so you can change it on the fly.

Thank you so much! So that function will show up in V5 at some point? I'm not sure about your question of what style of implementation. I just know that when I slid it to 0.01 or a bit more, I could keep the denoising lower for keeping a more consistent look, and have the animation go longer before turning into some sort of mess. I assume because it's putting in noise to replace some lost from denoising, but I have no idea.

**Comment by Animator-Anon** [comment]
It's back in there now.
