### ISSUE TITLE
Generate movie on interrupt

### ISSUE THREAD

**Issue by i2chris** [Animator-Anon/Animator#3]
Thanks for your work on this - it works really well.

It would be nice if the script would automatically generate the final movie even when it is interrupted by the user.   At the moment, if I want to interrupt the script, for whatever reason, then afterwards need to remote desktop into the windows server and manually run makemp4.bat so I can view the video.

It would also be nice if the batch file was created before all the files and it could be run at any time while the script is running. This would be useful when I'm generating a very long animation that will take ages to complete and I want to see what the video looks like before it is finished.

Thanks

**Comment by Animator-Anon** [comment]
I used to have it do this, but it takes a while to build the webm and I didn't want to wait for ffmpeg to finish before I could generate again. Every second counts and it can take 30s or so to create the video file sometimes and the UI waits for it to return before finishing up. I suppose I don't need to wait for the videos to be created to return from the custom script, that should sort that out. I'll try fixing that later on today.

Making the bat files first shouldn't be an issue either. Although you'll still have to remote desktop in, or install ffmpeg on your local machine. Would that work?

**Comment by Animator-Anon** [comment]
Should be sorted.

**Comment by i2chris** [comment]
Excellent.  If the delay becomes too big for some then you could make this an optional behavior by making the user click a checkbox labeled "Save when interrupted?"
