### ISSUE TITLE
[Feature Request] Frame to frame interpolation 

### ISSUE THREAD

**Issue by U1ongit** [Animator-Anon/Animator#30]
First off, I'd like to thank you for an excellent tool that I've spent many hours with.

My question is this, would it be possible to add interpolation models(like FILM) to the script to get those incredibly satisfying frame to frame  transitions.
Frame smoothing works great but doesn't quite hit the spot. 

However I can completely understand if this is outside the scope of this project 

But again, thank you for a fantastic tool.
/U1

**Comment by Animator-Anon** [comment]
I can add some different methods, the groundwork has been laid to a degree.
I am a bit wary of dropping in large projects or stealing other people's code. Some projects involve training specific ai models and stuff, I am probably too dumb and don't have to time to go that far.
I will start looking at some simpler methods.

**Comment by Animator-Anon** [comment]
Started having a play with film. If you get it set up and installed, you could move the images over to it's photo folder and run the video creation example prompt. It takes the frames in alphabetically and renders a video.

**Comment by Animator-Anon** [comment]
[test.webm](https://user-images.githubusercontent.com/114563845/198862024-92411dc5-09fe-4417-8009-83bcc055acd0.webm)
4 seconds, at 4ps, fed into FILM with --times_to_interpolate 4

prompts:
0 | seed | 11111111
0 | prompt | cat| 
4 | seed | 333333
4 | prompt | dog|

**Comment by Animator-Anon** [comment]
[20221030140616.webm](https://user-images.githubusercontent.com/114563845/198862169-a19ec800-fd01-4b59-8891-708c72869f45.webm)
To be fair, here is a frame smoothed version! Bit of a torture test.

**Comment by U1ongit** [comment]
Oh man, you're touching on pretty much exactly what I had in mind and you bring up a good point with the example prompt, hadn't thought of using it like that. I need to try it.
I have to admit that I'm squeezing up against the wall of the box of what is my technical knowledge so I really appreciate your time! Tbh It's probably about time I learn python :D

**Comment by U1ongit** [comment]
After a bunch of trouble I managed to get it set up. And I think it's really promising with a couple of caveats. 
FILM takes ridiculously long when processing a big set of images even at low interpolation. So I'd say it's better suited for smaller sets of just a few. It also seems like it's a lot better suited for calmer images and slow movement. 

Definitely worth to continue to explore

I'll include a few examples below where I tried it on a couple of past projects and a simple 4 frame sequence i generated and ran with --times_to_interpolate 6



https://user-images.githubusercontent.com/116985890/198900606-8fddcf96-fd69-4d7e-ba3c-abe9c4848324.mp4



https://user-images.githubusercontent.com/116985890/198900612-5c7616ee-21ca-40ee-876b-85296eb00eea.mp4


https://user-images.githubusercontent.com/116985890/198900620-05fb4444-fa38-4d9a-9aa5-04c0563f18e9.mp4

**Comment by Animator-Anon** [comment]
The main issue I have seen is it treats every set of frames individually. The morph motion doesn't flow consistently through the animation.  This may be fixed going under the hood, something I haven't tried yet. Probably a bit over my head.

The other thing is, google and other research outfits look to have come up with a way to animate stable diffusion. Probably better to wait until this comes main stream.

**Comment by U1ongit** [comment]
Exactly. It doesn't look ahead of the pair of frames it's processing at all and the animation ends up "wobbly". 
I'll try to do some research tomorrow and I can come back to you if I find anything and you feel up for it.

Oh that's exciting. Do you happen to have any articles on it?

**Comment by Animator-Anon** [comment]
https://imagen.research.google/video/
Haven't looked for any code yet.
