### ISSUE TITLE
Question/Issue: Not able to animate import footage

### ISSUE THREAD

**Issue by abstracti0** [Animator-Anon/Animator#31]
Hello i was making a sequence and wanted to import it in and do the animation onto it.

When i import using, using 

   0| source | images | D:\projects\...\*.png
   1| transform | 20| 0| 0| 90 <<< will not apply

Denoising Strength (overrides img2img slider) = 0.1
  
   >>> img2img_mode is on<<<

i am unable to apply any animation to the sequence. 
-------------------------------------------------

Is there a way to import an already made png sequence or footage and animate it?
When i try any other method it does a still image instead of sourcing the actual file. The animation is present only on the still image 
     not actual footage/sequence

**Comment by Animator-Anon** [comment]
It's easy to animate an image in a closed loop. you move it a small amount, process it, grab the result, move that a small amount etc.
In an open loop, you read an image or frame, move it a small amount, process it, save it to disk, grab next frame, move that a small amount.. Your animation or transform resets back to 0 every frame. I would have to sum up the transform parameters over time and apply them to the frames. but very quickly, if you zoom or pan around, you will lose your image very quickly.

How do you envisage it will work?

**Comment by abstracti0** [comment]
Im a little lost here.. your saying i animate by frame then?

0| source | images | D:\projects...*.png
1| transform | 20| 0| 0| 90 <<< will not apply
0| source | images | D:\projects...*.png
1| transform | 20| 0| 0| 90 <<< will not apply
0| source | images | D:\projects...*.png
1| transform | 20| 0| 0| 90 <<< will not apply

**Comment by abstracti0** [comment]
>>Your animation or transform resets back to 0 every frame.<<
This would mean that i would have to tell the image to start a specific point, call that image, then apply new transform to it, then process it?

**Comment by Animator-Anon** [comment]
This might be the case where I disabled the transform because it didn't make sense, to me, to use it in this situation. But this goes against the idea of this script, which is a toolset to allow people to do stuff. I will re-enable it, then at least people can try it and see what happens.

**Comment by abstracti0** [comment]
I greatly appreciate it, that feature brings a whole different aspect to the program!!!

**Comment by Animator-Anon** [comment]
Did you get the result you were after?

**Comment by abstracti0** [comment]
Im just waking up and will be testing this asap for you. THANK YOU SOOO MUCH!!!

**Comment by abstracti0** [comment]
So far its working flawlessly thank you again!

**Comment by Animator-Anon** [comment]
Great stuff!
