### ISSUE TITLE
Missing style for Poper folder

### ISSUE THREAD

**Issue by Harvester62** [Animator-Anon/Animator#32]
I noticed that at row 268 of animation_v6.py the paragraph style is missing and therefore the description text "Props, Stamps" is not correctly visible.

The line reads as follows

        i5 = gr.HTML("<p>Props, Stamps</p>")

but it should be as follows

        i5 = gr.HTML("<p style=\"margin-bottom:0.75em\">Props, Stamps</p>")

**Comment by Animator-Anon** [comment]
You are right, I wondered what those styles actually did, I think i took them from the example. Fixed now.
