### ISSUE TITLE
Everything is tinted...blue?

### ISSUE THREAD

**Issue by jet3004** [Animator-Anon/Animator#33]
Using v6, simple keyframe line '1| source| video| /Users/jet/Downloads/ginger.mp4' and just one 'style' positive prompt with low denoising...My results are good but for some reason, despite sampler or model or "Apply color correction to img2img results to match original colors" enabled/disabled, all my images are...blue. Especially noticeable in all faces. Kind of funny but can't figure it out and only happens when I'm using the Animator script. Maybe it's something simple I am missing?
![20221109005743_00161](https://user-images.githubusercontent.com/106498013/200808565-2fba9c94-dd99-44f5-ba87-3c1fe015788e.png)
![20221109020003_00003](https://user-images.githubusercontent.com/106498013/200808575-bde38da4-2527-4813-8ff8-1f6cdf935689.png)

**Comment by Animator-Anon** [comment]
Funny, I'll have a look. Colour correction should be turned off for all but img2img mode, but maybe I need to colour correct every frame.

**Comment by Animator-Anon** [comment]
OpenCV2 seems to now read video in BGR mode, I converted it. Let me know how it goes.

**Comment by jet3004** [comment]
Worked! Thank you so much! Now if only I could work out less flicker...

**Comment by Animator-Anon** [comment]
Lower denoise I guess, but then you end up with no changes. It's a tough one.
