### ISSUE TITLE
Initial Image

### ISSUE THREAD

**Issue by abstracti0** [Animator-Anon/Animator#34]
Hello again, i seen there was an update today and went to check it out. Im noticing its making an initial image now from the frames. Why is it doing this if im feeding it already made images?

**Comment by Animator-Anon** [comment]
It's possible I broke it. Are you feeding it a folder of frames or a video using the source command?

**Comment by abstracti0** [comment]
i wasnt using the source command, i was using the ui  batch img2img folder link. I will try with the source command and see

**Comment by Animator-Anon** [comment]
I need to see the keyframes you typed in, feel free to sanitise if needed.

**Comment by abstracti0** [comment]
0| source | images | D:\projects\harmonic\build_v3\build_v3_****.png 
![Screenshot (14)](https://user-images.githubusercontent.com/114834484/201501560-b7e317bc-5eab-49ac-b3ea-aa596d06d5d1.png)

**Comment by abstracti0** [comment]
its also starts to render again even after it has finished the first pass

**Comment by abstracti0** [comment]
if i use the version before the update it doesnt have the initial file

**Comment by Animator-Anon** [comment]
I must have left the debugging option on, those initial images can be deleted.
Not sure the multiple *s are needed in the path. I'll give it a test run to check I didn't break something.

**Comment by abstracti0** [comment]
i was planning on to delete of those but im kinda run on space atm but its temp fix. 
im just use to labeling like that smh but ill try it with 1 *.
the rerender issue is a hassle tbh, sometimes i walk away or let it render while i sleep and it will not stop rendering lol

**Comment by jet3004** [comment]
This is happening for me, too, each time it is adding the initial image.

**Comment by Animator-Anon** [comment]
This will be due to the total animation length. It should try to render total_animation_length * fps frames. If it runs out of source frames, it will repeat the last frame. That's what I programmed anyway.
I dragged in an unrelated initial frame, a filthy city:
![city](https://user-images.githubusercontent.com/114563845/201502375-0186906c-2f54-463a-8cc7-bccc824ecca6.png)

Got a video and extracted 100 frames into a folder. Left total length at 10s, set FPS to 25 to match source video.
Using the following keyframes:
0 | seed | 12345
0 | source | images | d:\temp\*.png
0 | prompt | academy award winning actor | 
0 | denoise | 0.2
10 | seed | 12345

Notice I have fixed the seed by setting the start and end seed to the same value.
Got the following video. When the seed is fixed and the source frames are the same, you get the same output frame, hence the video looks like it freezes.
[20221113121452.webm](https://user-images.githubusercontent.com/114563845/201502471-dcbaf3ac-9278-48ed-918c-769b7757ae4c.webm)

**Comment by abstracti0** [comment]
i have it set to 96 seconds for 1146 frames. its repeating the entire range from start. it creates a new folder in img2img and starts from the first input frame

**Comment by abstracti0** [comment]
this is the last video i made with your tool before you added the frame animation back. this new video should be alot better https://www.instagram.com/reel/CkRQjsTJch4/?utm_source=ig_web_copy_link

**Comment by abstracti0** [comment]
also at .25 zoom it does this, is there a way you could eventually tile the image so it also fills in those areas or allow it to have a little more enhancement to image. It is an improvement from the v5 before it would just be black on the outside
![Screenshot (2)](https://user-images.githubusercontent.com/114834484/201503975-9b968cec-4aae-4350-80ef-036f5d819776.png)

**Comment by Animator-Anon** [comment]
Alright lets work one bit at a time. I turned off the dumping on initial images, that was just for testing.  i turned it of when fixing the blue videos and want to see the image before it gets processed.

> i have it set to 96 seconds for 1146 frames. its repeating the entire range from start. it creates a new folder in img2img and starts from the first input frame
So you have 1146 frames in the source folder, and you are trying to create an animation with more frames than that? And at frame 1147 it repeats the image sequence from the start again? That shouldn't be happening.
globbing is used to build a file list from the supplied path and wildcard. This could be failing for some reason.

**Comment by abstracti0** [comment]
-- "I turned off the dumping on initial images" <<< this is fixed
-- you are trying to create an animation with more frames than that << no i want it to stop at 1152(96sec), which it does but when it completes the final frame the program creates a new folder and starts the process over again. It will count down to 0 and reset the counter to 59 sec and continues to do this with no end.

-- Another issue is that the scaling and rotating seems to also be broken : when using >> time_s | source | images | path, with Img2img_mode checked 


7.0| transform | 10 | 1 | 1 | 1
7.5| transform | 200 | 0 | 0 | 900
8.0| transform | 50 | 0 | 0 | 250
8.5| transform | 10 | 1 | 1 | 200

^^^^^ this does nothing even if i set it to 

7.0| transform | 1 | 1 | 1 | 1
7.5| transform | 20 | 0 | 0 | 90
8.0| transform | 5 | 0 | 0 | 25
8.5| transform | 10 | 1 | 1 | 20

^^^ the zoom and rotation will be the same

The zoom factor doesnt work even if set to 100, i think this is bypassed when using the transform command

-- Im not sure if im using it wrong, maybe its suppose to work this >>> time_s | source | img2img | path

**Comment by abstracti0** [comment]
normally when you do this with just img2img it works smooth with the zoom in and out and the turn but this is what its producing

https://user-images.githubusercontent.com/114834484/201512296-a4fad215-fe5d-4d94-9163-4ec74ab8f2a7.mp4

**Comment by Animator-Anon** [comment]
Do you have batch size set? It should all be nulled out.. Maybe I will try a longer example and see what happens.

This is fairly normal. Even though you are in img2img mode, if you specify an image source like a video or a series of pictures, these are fed in each frame instead of recycling the same initial frame.

**Comment by abstracti0** [comment]
this is using the same keyframes but without using the >>>> time_s | source | video, images, img2img | path

https://user-images.githubusercontent.com/114834484/201512415-ffc0d2e6-5e2c-4d9d-a0bd-d51c3e2c68e7.mp4

**Comment by abstracti0** [comment]
Do you have batch size set? <<< what do you mean as in the gui its set to the proper size 512/704

**Comment by Animator-Anon** [comment]
Yes, do you understand why this is happening?
In the latter example, the output is transformed and fed back into the input, so it can keep working on it.

You can't do that with a video source, because it is providing each input frame. They don't get processed and fed back in, so changes don't flow from one frame to the next.

**Comment by abstracti0** [comment]
i really dont understand tbh, im guessing that its not morphing the last and next frames together from what im understanding??

-- You can't do that with a video source, because it is providing each input frame. They don't get processed and fed back in, so changes don't flow from one frame to the next. << is there a way to eventually be able to do this?

**Comment by Animator-Anon** [comment]
That is correct, they aren't morphed together. I don't know how that would work and haven't tried experimenting with it
. If you can think of a way that would work, I can try it.
I could try do a 50/50 mix of last frame to first frame, see what happens. I don't have high expectations for it though.

**Comment by Animator-Anon** [comment]
> Do you have batch size set? <<< what do you mean as in the gui its set to the proper size 512/704

I was more thinking the batch count & size fields. I tend not to use batch size and just leave it at 1. It might be something I haven't tested.

**Comment by abstracti0** [comment]
do you think sourcing the frames while doing it as img2img will allow it to morph into each other
0 | source | img2img |0.png
0.5 | source | img2img |6.png
1 | source | img2img |12.png

--ive used the stamp before and it covers the image.. im not sure about the prop, i have tried it a few times but i didnt see too much of it, maybe if allowing the prop to stay on screen like the stamp does might force it to morph, or start with prop and turn the prop on and off, while swapping out props

0| prop | fram0 | 0.png | x pos | y pos | scale | rotation
.9| clear_prop | fram0
0.9| prop | fram11 | 11.png | x pos | y pos | scale | rotation
1.9| clear_prop | fram11
1.9| prop | fram23 | 23.png | x pos | y pos | scale | rotation


 like it puts the image up and morphs then is swapped out for a different frame

**Comment by Animator-Anon** [comment]
It doesn't make sense to source the frames from somewhere else in img2img mode. I don't think there is a way to do this currently, I'll have to try some stuff.

Stamps, like text blocks, are applied in post processing, and are only put on the images saved to disc.. The exist until you clear them.

Props are burned into the image in pre-processing one time, so the img2img can incorporate them and work on them. They won't do much in video or images mode, since it isn't closed loop.

**Comment by abstracti0** [comment]
--Props are burned into the image in pre-processing one time... what about allowing props to be pulled in as a seq? or a setting to allow them to stay on for longer than one frame?? I would be able to source frame 0 then apply the prop according to frame number on top of it of the next few frames forcing it to accept the images in the closed loop

**Comment by Animator-Anon** [comment]
> --Props are burned into the image in pre-processing one time... what about allowing props to be pulled in as a seq? or a setting to allow them to stay on for longer than one frame?? I would be able to source frame 0 then apply the prop according to frame number on top of it of the next few frames forcing it to accept the images in the closed loop

stamps

**Comment by abstracti0** [comment]
even if its 12 fps dumping 6 frames on top of the 0 frame should create the effect. im thinking that when its necessary source another frame like frame 48 and start the process over of putting the next few frames over it as props

**Comment by abstracti0** [comment]
stamps dont morph though

**Comment by abstracti0** [comment]
pretty much trying to trick the system into accepting the next frames in the closed loop

**Comment by Animator-Anon** [comment]
> pretty much trying to trick the system into accepting the next frames in the closed loop

Well in that case you could use a prop. Have you tried? If you set it such that it fills the entire frame I don't see why it wouldn't work.

**Comment by abstracti0** [comment]
i tried it on the first video but i didnt really understand what i was doing back then. i have alot better grasp on things now. give me a few min ill try it right now

**Comment by abstracti0** [comment]
0 | prop | frame_0| build_v3_0000.png | 0 | 0 | 100| 0
.25 | prop | frame_3| build_v3_0003.png | 0 | 0 | 100| 0
.5| prop | frame_6|  build_v3_0006.png | 0 | 0 | 100| 0
.75 | prop | frame_9| build_v3_0009.png | 0 | 0 | 100| 0
1 | prop | frame_12| build_v3_0012.png | 0 | 0 | 100| 0


what is the default x pos | y pos to allow the image to align in the center?
