### ISSUE TITLE
[Feature Request] Some type of .VTT/.JSON to prompt import?

### ISSUE THREAD

**Issue by jet3004** [Animator-Anon/Animator#35]
I am not exactly sure how the results would fair but it would be **very** cool if you could import a standard .vtt/.json video transcription file a la keyframe source as easily as "_0 | subtitle |  /xyz/videosubtitle.json_" and then have each time stamped words (since that's the benefit of .vtt/.json over .srt) to create a new prompt easily mapped to that exact time stamped word, for the duration of the video?  Does that make sense? Want to make sure I'm articulating this right.

**Bonus** is that it could be used with or without an initial image/video, providing advantages to both – so interesting results whether you are 'recreating' a scene from almost nothing in a txt2img way (well, I always use your script for the direct .mp4s) **OR** using it for img2img way to more accurately prompt the a source video second by second.

**Comment by Animator-Anon** [comment]
Can you make an example?

**Comment by jet3004** [comment]
Sure! So like this small (dumb) video + its small auto-generated .json (which I transcribe locally for a lot of videos) which is similar to VTT (which mostly go with YouTube videos). So then it could allow you to change the prompt (plus keep positive prompt at beginning) down to the SECOND with whatever keyword is mapped to the timestamp in the subtitle folder. So you'd key something like

```
0 | source | video | /xyz/hell.mp4
0 | prompt | Normal Rockwell style
0 | subtitle | /xyz/hell.json

```

With the end results being gif/webm/mp4 of the video with a slow of prompts based on timestamps, resulting in varying lengths and weird 'scenes' like "_Normal Rockwell style, sure now you see why i start fighting_" at 32.82 seconds in, etc, etc. Insane? Maybe! But would be cool and seems like the ground work would is all there.

[hell.zip](https://github.com/Animator-Anon/Animator/files/9998479/hell.zip)

**Comment by Animator-Anon** [comment]
I'm gonna take the super lazy approach and add support for .vtt (WEBVTT) files. Much easier to read than trying to load in the json file.
The subtitle lines themselves should be in the format of:
   positive prompts | negative prompts
The positive and negative prompts will be set at that time. Templates and all the other stuff still applies.

**Comment by Animator-Anon** [comment]
Uploaded a test version with these changes.

**Comment by jet3004** [comment]
@Animator-Anon Awesome, thank you!! I will test soon then -- is it just .vtt or .srt too? 

Ok so it would still use the single digit seconds keyframe even those the subtitles files parse them differently? Can you write out a direct example if I had, say, a 10 movie named test.mp4 with corresponding subtitle test.vtt I wanted to used one positive prompt of "beach scene"  (and I low denoting for?)


 Appreciate your help on this!

**Comment by Animator-Anon** [comment]
I made this example:
```
WEBVTT

00:00.000 --> 00:02.000
cat | dog

00:02.000 --> 00:04.000
dog | cat

00:04.000 --> 00:06.000
eagle | fire

00:06.000 --> 00:08.000
fighter jet | person

00:08.000 --> 00:10.000
scone | animal
```

**Comment by Animator-Anon** [comment]
The time values in standard prompts can be floating point values, you could write for example:
```
0 | prompt | car | 
0 | transform | 2| 0| 0| 0
2.5 | transform | 1| 100| 0| 0
4.122 | transform | 1| 0 | 100| 0
6.667 | transform | 1| -100| 0| 0
8 | transform | 1| 0| -100| 0
10.0 | transform | 0.5| 0 | 0| 0
```

**Comment by jet3004** [comment]
@Animator-Anon Thank you so much for this! Really! I am slightly confused – I assumed that the .vtt support would bring in the ability to essentially have the subtitle transcriptions -> prompts, so if the VTT said at "2.3 seconds" someone said "The girl in a barn" it would inject that as positive prompt (and wouldn't need a neg prompt but we know that could help with results) and then next transform would be automatically at "5 seconds" with the subtitle "Saw an owl in the corner" - is that possible with this or would I still need to manually key each frame? I guess I was hoping that a subtitle track could cut out a lot of transcription and key framing, basically, and create grand abstract results out of longer/feature length video files.

**Comment by Animator-Anon** [comment]
Yes that is the intent and what I tried to do.
When the VTT file is processed, a prompt keyframe is built for each valid entry in that file. No need to add them into the keyframe list. You may still need to set the templates if you want to use them, these will be unchanged.
If it is not working and silently doing nothing, the formatting may be an issue, post an example here and I will take a look.

**Comment by jet3004** [comment]
Sorry, I guess I'm just super confused! Where in the keyframes am I entering my .vtt? I have a 4:10 .vtt I want to do a loose visualization for around the subtitles from start to finish...I thought I'd do something like this and it would  
`0 | prompt | /Users/jet/Downloads/angel.vtt` and that's what I would need, unless I have to dually put it all in? Appreciate your help.

**Comment by Animator-Anon** [comment]
Oh right I added a new keyframe for that. I probably didn't mention it but did update documentation.
You'd do this:
0 | prompt_vtt | /Users/jet/Downloads/angel.vtt

The time doesn't matter, but it needs to be there for the general keyframe processing, so setting it to 0 is fine.

**Comment by jet3004** [comment]
> Oh right I added a new keyframe for that. I probably didn't mention it but did update documentation. You'd do this: 0 | prompt_vtt | /Users/jet/Downloads/angel.vtt
> 
> The time doesn't matter, but it needs to be there for the general keyframe processing, so setting it to 0 is fine.

Ahhh, there it is, ha! I tried for days and didn't want to ask till I was sure. Will test this more tonight but -- in this made up quick test with the .vtt file ( which I double verified works and is accurate), I am not seeing the subtitles-> prompts, this is the output. 
<img width="1662" alt="coco" src="https://user-images.githubusercontent.com/106498013/204365346-7baa055a-7df8-409f-ab17-a59b775003ce.png">


Am I missing something obvious? Thanks for this!

**Comment by Animator-Anon** [comment]
It is currently interpolating between "modern disney style" and "modern disney style".

**Comment by jet3004** [comment]
> It is currently interpolating between "modern disney style" and "modern disney style".

Yes, how do I get the 'master' positive prompt to input alongside the .vtt captions? I don't see those anywhere so not sure I have the right keyframes but using your direction above.

**Comment by Animator-Anon** [comment]
You can either fill out the template fields in the UI, just above the keyframe box.
Or you can use the template keyframe:
```
0 | template | (cinematic lighting), (hand drawn sketch) | 3D, render
0 | prompt_vtt | /Users/jet/Downloads/angel.vtt
```

Assuming your VTT file looks like this:
```
WEBVTT

00:00.000 --> 00:02.000
cat | dog

00:02.000 --> 00:04.000
dog | cat

00:04.000 --> 00:06.000
eagle | fire

00:06.000 --> 00:08.000
fighter jet | person

00:08.000 --> 00:10.000
scone | animal

```

You will get the following resulting prompts:
Time 0.00s:
Positive: (cinematic lighting), (hand drawn sketch), cat
Negative: 3D, render, dog

Time 2.00s
Positive: (cinematic lighting), (hand drawn sketch), dog
Negative: 3D, render, cat

etc

The other factor is these prompts will be interpolated together. At time 0, you will solely get the first prompt. At time 1, you will get 50% of the first prompt, 50% of the second prompt. At time 2, you will get 100% the second prompt.
