### ISSUE TITLE
Hello hello!! KUDOS to this AMAZING SCRIPT!!! I just have one question

### ISSUE THREAD

**Issue by LIQUIDMIND111** [Animator-Anon/Animator#36]
Is there a way to use math like in deforum that reads like this: 0:(0.55*sin(2*3.141*t/500))

or any math that you can use to make soft camera movements, OR any template you have for people to use for soft panning? in which maybe users only edit the TIME SECONDS but you make the camera codes... you can even sell them :P hehe 

NOTE: animator 6, since it uses IMAGE TO IMAGE, and ALSO, since i use a custom model for iterations, i get a WAY BETTER COHERENCE. than using regular models///

**Comment by Animator-Anon** [comment]
Off the top of my head, if you add enough transform keyframes, it will start doing a polynomial interpolation on them, which will give you smoother transitions. I think you need at least 4 including the start and finish. Check the .csv file in the output folder, open it in excel and plot a parameter to see how it did.
I might be too dumb to add support for math functions, but it might not be necessary. Creative use of keyframes should give you similar results?
or do the equations come from somewhere else, software wise?

Different models you say? Like a full on different checkpoint? Did you train it yourself?

**Comment by LIQUIDMIND111** [comment]
Hello sir. i will reply in order:

1) Yes i am using 4 key frames at the moment, doing well, even better than i was expecting, that script has surprises.....

2) the math formula are done on https://docs.google.com/document/d/1pfW1PwbDIuW0cv-dnuyYj1UzPqe23BlSLTJsqazffXM - and i used this example they have 0:(10*sin(2*3.14*t/10)) and edited it to my preference.... also using AUDIO to KEY frame generator https://www.chigozie.co.uk/audio-keyframe-generator/ i learned a lot on how to READ the math formula... but i do not know how to write them from scratch.

3) YES, creative use of key frames will do the same..... i just so hard to sit down and be testing camera angles with 1.2 1.5 0.7 etc..... its very tiring.... so these math codes they do it automatically.... like this animation i made yesterday in DEFORUM, https://www.youtube.com/watch?v=cc8DEEZBZBI in which you can see the slow beautiful camera movements..... so i wish to learn to do the same with your script.....

4) YES i used also a custom dream booth model for my animations, and i will explain why, this is the longest reply but it will help you with my feedback.

DOING ANIMATIONS IS NO PROBLEM, the main issue now is using a VIDEO SOURCE like this: 
https://www.youtube.com/shorts/XMPkSm6Sh8w SORRY i cannot upload videos more than 10MB, i can reference the link since its from PIXABAY or PEXELS, (https://www.pexels.com/video/woman-smiling-for-the-camera-7049300/)  but i had to mask her face because the flickering is too much using IMAGE TO IMAGE.....

NOW, IF YOU USE A CUSTOM MODEL, it will keep coherence ALL THE WAY, but might miss some face expressions like small smiles or mouth opening...... anyway, with YOUR script, i tried BATCH IMAGE INPUT with this same video original frames, and the result was an amazing NON-RELATED WOMAN, but awesome art... so it changed the person, into a whole new thing..... do you know yourself that you can make BATCH IMAGE INPUT with your script? LOL anyway, do you know how to keep coherence of the person? the face Won't CHANGE, but oh boy... its hard to explain, i might have to upload some videos at YouTube so you can see......

**Comment by LIQUIDMIND111** [comment]
another thing, the slow frames in-between that you added for smoothness, is a HUGE THANKS!!!!

**Comment by LIQUIDMIND111** [comment]
hold on, i forgot!!! i made this yesterday ONLY with animator script v6!!!! look, it came very nice for me being a rookie with your script.....

https://www.youtube.com/watch?v=mp5Q66Zb6d8

**Comment by LIQUIDMIND111** [comment]
![Screenshot 2022-11-21 143207](https://user-images.githubusercontent.com/112510084/203132943-52a8b633-b079-4195-baf6-2b83c6a311ad.jpg)


bro, i apologize, forget my last comment about coherence, THIS IS TOO MUCH, your script can turn any FRAMES INPUT after 3 seconds of original footage, it converts it into a AMAZING piece of arts, AND animate in the latent space through it.... WHAT ELSE CAN YOU ASK....?? bro.... nice job...

**Comment by Animator-Anon** [comment]
Thanks for kind words, most of the magic comes from the work of others. This is just a toolset that allows you to mess around with things!
