### ISSUE TITLE
Hello, x and y shift on animator 6 seems not working correctly.

### ISSUE THREAD

**Issue by LIQUIDMIND111** [Animator-Anon/Animator#37]
![Screenshot 2022-11-21 180537](https://user-images.githubusercontent.com/112510084/203167487-3b147fd7-4737-4ae3-a6f9-6c21f569cae1.jpg)
 i am doing a test and the zoom does works, but there is no shifting whatsoever.... only goes back and forth if i add key frames with zoom on 0.5 .... rare..... the other day, shifts did worked.... any clue? whats the highest number you can use?

**Comment by LIQUIDMIND111** [comment]
and how to you turn RIGHT? LEFT is 1.2 and RIGHT is 0.6 ???

**Comment by LIQUIDMIND111** [comment]
> You have told it to move 2 pixels per second. That isn't very fast, Try 200. Negative number to move the other way.

negative to move the other way? but on ZOOM to go BACK you use 0.5 right?

**Comment by Animator-Anon** [comment]
Yes, zooming is scaling the image by a percentage, shifting is shifting it by a number of pixels.

**Comment by LIQUIDMIND111** [comment]
bro, i am giving your script a nice promo 👯 , check this one made only with animator.

https://www.youtube.com/watch?v=TwX7ZXnUANM&ab_channel=LiquidMindArts%26Music111

**Comment by Animator-Anon** [comment]
Nicely done, some real dream sequence animations, plenty of light blooming.
I am happy to see people make stuff.
