### ISSUE TITLE
Request: CFG Scale adjustments keyframe

### ISSUE THREAD

**Issue by Northloop** [Animator-Anon/Animator#39]
Amazing work! If there's a way that you could add CFG scale adjustments on the fly like you do with models, that would be amazing.

**Comment by Animator-Anon** [comment]
Is that something you would want interpolated? Should be easy enough.

**Comment by Northloop** [comment]
It would be nice. I test run images before making a video. And sometimes I like what I'm seeing with a lower CFG scale and other times, I'm really into a higher CFG scale's outcome. It would be nice to be able to dial that in and change it throughout a video :)

**Comment by Animator-Anon** [comment]
Try the test script, see how it goes. New keyframe for cfg_scale, will start at the GUI value and interpolate between the values you set.

**Comment by Northloop** [comment]
That's really awesome! Thank you!
