### ISSUE TITLE
Feature request: Image Props

### ISSUE THREAD

**Issue by 93892** [Animator-Anon/Animator#4]
I would like the ability to have a "props" folder of images ranging from fire & explosions to cats, apples etc. These image "props" are simply pictures of isolated objects saved as transparent png files.  Similar to keyframes, I would like an interface where I can specify the time, location and other settings for a prop image to be overlayed onto a frame before it's passed to img2img. 

This would give us more control over the animations and enable a lot of storytelling possibilities.

**Comment by 93892** [comment]
Configuring a prop could be similar to your keyframe format:

Prop Name | Time to overlay it | Location x | Location y | Scale | Frames to overlay it for | Add to Positive Prompt Words | Add to Negative Prompt Words

**Comment by Animator-Anon** [comment]
It's a pretty good idea and doable I think. let me meditate on how to work it in.
I may have to expand the keyframe mechanic into a command style mechanic...

**Comment by Animator-Anon** [comment]
Check out v2 script. At this stage, props are embedded into the picture, so will be diffused in the next frame, rather than stamped on the image saved to disk. Will work on the latter feature later when I get pandas figured out.
