### ISSUE TITLE
AMAZING SCRIPT!!! ONE OF THE BEST SCRIPTS FOR STABLE DIFFUSION!!! LOOK AT THIS RESULTS!

### ISSUE THREAD

**Issue by LIQUIDMIND111** [Animator-Anon/Animator#40]
https://www.youtube.com/watch?v=H9fVs9GpRis&ab_channel=LiquidMindArts%26Music111

Enjoy 3:33 minutes of visual relaxation with this original arts video made with self drawn arts by hand then synthesize in AI to produce a more deep look into my own arts, and finally make a STYLE MODEL of my arts and THEN remix that model with ANOTHER model that I have, and the results are these amazing gorgeous colors and lights that will relax you and even hypnotize you and help you ease away all problems for a moment..... safe trip :D

**Comment by Animator-Anon** [comment]
Is this what it's like to eat a bag of mushrooms?

I have experimented with feeding lines of a poem into a script, but I think I lack a fair bit of artistic talent. I can't get anything close to this in surrealism.

**Comment by LIQUIDMIND111** [comment]
> Is this what it's like to eat a bag of mushrooms?
> 
> I have experimented with feeding lines of a poem into a script, but I think I lack a fair bit of artistic talent. I can't get anything close to this in surrealism.

YOU ARE THE MAN. one trick is, MAKE A CUSTOM MODEL with STYLES made in mid journey or any other place, and use that model to make arts. look what i just did, an OUTPAINTING of a custom model i made..... i can help you in any case.... dreambooth is your friend. :)
![Untitled-1](https://user-images.githubusercontent.com/112510084/204410033-c0c1417d-2168-4931-b717-32f2869ac88f.jpg)

**Comment by DigitalxDreams** [comment]
hey can you provide any example keyframe documents or setups?

I am having a lot of trouble getting things to work good.

for example: I send over a picture of cat to Img to img tab.

Then i put in the keyframes box.

0 | prompt | dog |

I wanted the cat to start morphing into a dog at the beginning. But it just keeps making new cats and they dont even blend together.

do you have any good keyframe setups? or easy explanation?

**Comment by Animator-Anon** [comment]
That is insane, I need to do some reading up. I keep hearing about dreambooth but have no idea what it is. But you can't argue with the results, it has generated a bunch of seamless additional content.

**Comment by Northloop** [comment]
> That is insane, I need to do some reading up. I keep hearing about dreambooth but have no idea what it is. But you can't argue with the results, it has generated a bunch of seamless additional content.

Dreambooth is pretty amazing if your GPU can handle it. Openart.ai has a paid service to train that I've tried out with good results. I'm getting a 4090 this week so I can really get in the goodness of your script and training models :)
