### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Waz999** [Animator-Anon/Animator#43]
Thanks for creating this by the way. I love using it! Just wanted to know - would there be any way to influence the progression of the subject within frames with prompts? Random example: By loading an initial image of a car into img2img and wanting it to morph into a helicopter by the final frame?

Thanks again and keep up the good work!

**Comment by Animator-Anon** [comment]
Probably nothing clean, but prompt interpolation might be the go. You could manually use it txt2img page of webui by using the following positive prompt:
car:0.75 AND helicopter:0.25
Vary the percentages to see the intermediate stages.
In my script, if you have prompt interpolation turned on, it will move between prompts in this manner, so you would just set a prompt at t0 and a different one at t10 for example:
0 | prompt | car |
10 | prompt | helicopter |

The quality of the results will vary wildly.

**Comment by Waz999** [comment]
Ok great thanks! I'll give it a go.

**Comment by Animator-Anon** [comment]
Look for the checkbox on my animator extension tab, called prompt interpolation. It is checked by default.

**Comment by Waz999** [comment]
I don't see it anywhere? Unless I'm looking in the wrong place?
![Capture](https://user-images.githubusercontent.com/75366820/209063154-2436213b-5186-4a17-906a-a14e27167b1b.JPG)

**Comment by Animator-Anon** [comment]
That looks like the old v6 script. It also does prompt interpolation by default, you just need to add two or more prompts in the keyframes section.
I have made an extension version of the script now, which can be installed. Check out the other repo I have if interested,

**Comment by Waz999** [comment]
Great thanks, will do!
