### ISSUE TITLE
Keyframe format

### ISSUE THREAD

**Issue by pvbg** [Animator-Anon/Animator#45]
Hello,
I have been using your script for a few days and it has worked great. But am new to this and coding and can't figure out how to enter the keyframes. I have attached an image of the field I see. Could you please give an example of a how to enter a keyframe, let's say for zoom. Also this is the Deforum web ui if that makes a difference.

That would be greatly appreciated.

![Schermafbeelding 2023-01-02 om 20 40 06](https://user-images.githubusercontent.com/121826652/210273011-6431d03c-b1d6-4220-b35c-e5b835df67be.png)

**Comment by Animator-Anon** [comment]
To zoom you would use the transform one.

You can copy the line from the template and change the values like this:
0 | transform | 1.5 | 0 | 0 | 0

At time zero, or frame zero, it will start a zoom in at a rate of 1.5x per second. So after one second, the image will be 1.5x bigger, sort of like you have zoomed in 50%. If that makes sense. Setting the shift and rotation parameters to zero means no shifting or rotation will be happening. These values need to be here though.

**Comment by pvbg** [comment]
Thank you, that worked.

I was trying to have multiple keyframes but I tried multiple lines, or comma's between numbers (200,400,600 | transform | 1.1 ,0.7,1.1| 0,100,0 | 100,0,100 | 5,5,5) and nothing works yet.

Is it possible to insert multiple keyframes?

If that is possible, is there a way to add multiple prompts? For example, at 200, 400 and 600, each having its own prompt list?

**Comment by Animator-Anon** [comment]
Ah no that wont work, just write the keyframe out again on a new line and change the values.
I.e.
0 | transform | 1.5 | 0 | 0 | 0
5 | transform | 1.0 | 0 | 0 | 0
10 | transform | 1.0 | -50 | -50 | 45
