### ISSUE TITLE
hello mate, animator is not working. Smoothing frames are broken no matter what size i do animation

### ISSUE THREAD

**Issue by LIQUIDMIND111** [Animator-Anon/Animator#46]
![Screenshot 2023-01-29 193920](https://user-images.githubusercontent.com/112510084/215362615-19634098-8802-49b9-a479-3f95e0e752a4.jpg)
any idea whats happening? i tried MANY MODELS from 512 512 to 768 768 and doesn work on IMAGE TO IMAGE SECTION

ALSO, the EXTENSION TAB SECTION does not works well because you have to make the first frame do A FULL STEP but all other frames need to do LESS STEPS and the animator script on the TAB section WONT create LESS STEPS, so animation is OK but jumping frames ... so i am reporting 2 issues......

**Comment by LIQUIDMIND111** [comment]
Uploading video.mp4… this is what happens then ALL FRAMES are made using the same steps as the first frame - in order to have the animations as before you need to enable this option  """With img2img, do exactly the amount of steps the slider specifies (normally you'd do less with less denoising).""""" it wont work on the TAB, but it will work on the IMAGE TO IMAGE SCRIPT SECTION but animations are broken as you can see in the photo..... so they BOTH are broken i believe,,,

**Comment by LIQUIDMIND111** [comment]
https://user-images.githubusercontent.com/112510084/215362798-3f7346f3-cc57-4964-8e78-dd58a09db33f.mp4

**Comment by LIQUIDMIND111** [comment]
UPDATED THE SCRIPT AND NOW SEEMS TO WORK< MY APPOLOGIES.

**Comment by Animator-Anon** [comment]
Ha I probably broke something. Happens all the time.

**Comment by LIQUIDMIND111** [comment]
> Actually that was webUI broke, it changed the image format internally from RGB to RGBA. I noticed a little while ago.

no problem man, thanks for all your attention.
