### ISSUE TITLE
images fading to black

### ISSUE THREAD

**Issue by ArtToyz** [Animator-Anon/Animator#47]
animator script for auromatic1111started rendering towards black by around frame 40. I am using deforum2.0b
![00041-1726664864](https://user-images.githubusercontent.com/114187785/218338854-ad8d8185-82be-486a-9365-20323f713d66.png)
![20230211174918_00071](https://user-images.githubusercontent.com/114187785/218338912-ce25dd6b-5378-4c0f-a241-7020c168b1ff.png)

**Comment by Animator-Anon** [comment]
What do you mean by using deforum2.0b? Are you using the automatic111111 webui?

This looks like the reverse of what happened a while ago, someone changed the code that applies colour corrections, and it washed out the image. My fix was to rip the old colour correction code out and handle it myself. 

Therefore, it doesn't seem related to that. I have to ask all the dumb questions, are you using the most up to date version of my script, are you using latest automatic webui?

**Comment by ArtToyz** [comment]
I thought decorum might be messing this up .It never did before. I am using the latest webui from automatic1111. Can't find color correction info in there. I will try this on my older setup and see if it is doing this there.
Animator is a cool tool. I think i,m using the only one and the instance labeled v6.
Thanks for caring.
This was working for a while with the latest interface I believe. The one you can watch draw.
________________________________

**Comment by Animator-Anon** [comment]
Generally, it's worth trying to run img2img in the webUI for the max frames/length possible, see if it produces similar results.
That is sort of what my script does. There is also a keyframe that can turn colour correction on or off. When you turn it off the image typically turns purple though.

**Comment by ArtToyz** [comment]
thanks man I am out of town now but on Friday I will give it a thorough run through

________________________________

**Comment by ArtToyz** [comment]
any way you could show me a 2 line animation script to translate z in the new Automatic 1111 Animation extension. I tried lots of ways and I guess I don't understand the context.

________________________________
