### ISSUE TITLE
Negative zoom in transform

### ISSUE THREAD

**Issue by kstroevsky** [Animator-Anon/Animator#48]
Hi! I try to set negative zoom into transform param `0 | transform | -1 | 0 | 0 | 0`, but unfortunately I get the following error. Do I do something wrong or is it a bug? 
```python
img2 = img.resize((int(w * zoom), int(h * zoom)), Image.Resampling.LANCZOS)
ValueError: cannot convert float NaN to integer
```

**Comment by kstroevsky** [comment]
I'm sorry. The right solution is `0 | transform | 0.5 | 0 | 0 | 0` because of percentage computing.

**Comment by Animator-Anon** [comment]
Yes! The zoom factor is actually a scale factor used to resize the image. Now you know the truth.
