### ISSUE TITLE
hello friend!!! ANIMATOR EXTENSION wont produce SMOOTH FRAMES

### ISSUE THREAD

**Issue by LIQUIDMIND111** [Animator-Anon/Animator#49]
Anything i need to do? i can manage to work, but wont make smoothing frames.......

**Comment by LIQUIDMIND111** [comment]
![Screenshot 2023-08-03 112850](https://github.com/Animator-Anon/Animator/assets/112510084/2e41df9c-0dae-4876-8cc0-7c5f19b0ef7f)


i even tried with FILM interpolation on.

**Comment by Animator-Anon** [comment]
I need more info. Any errors in the log/terminal?
FILM will only work if you have FILM installed.

**Comment by LIQUIDMIND111** [comment]
> I need more info. Any errors in the log/terminal? FILM will only work if you have FILM installed.

ok i UPDATED the extension and works now..... it was out of date..... sorry and thanks for being attentive.
