### ISSUE TITLE
KEYFRAMES Question

### ISSUE THREAD

**Issue by LIQUIDMIND111** [Animator-Anon/Animator#50]
Hello, im using this as keyframes.

1 | transform | 0.9 | 10 | -20 | 1
2 | denoise | 0.29
3 | transform | 0.8 | -10 | 20 | 1
3 | denoise | 0.22
4 | denoise | 0.29
5 | transform | 1.0 | 10 | -20 | 1
5 | denoise | 0.75
6 | denoise | 0.22
7 | transform | 0.8 | -10 | 20 | 1
7 | denoise | 0.29
9 | transform | 1.0 | 10 | -20 | 1

i want to know if can use decimals in the seconds, and will it work?

LIKE THIS:

1.5 | transform | 0.9 | 10 | -20 | 1
2.3 | denoise | 0.29
3.2 | transform | 0.8 | -10 | 20 | 1
3.8 | denoise | 0.22
4.2 | denoise | 0.29
5 | transform | 1.0 | 10 | -20 | 1
5.5 | denoise | 0.75
6 | denoise | 0.22
7 | transform | 0.8 | -10 | 20 | 1
7.5 | denoise | 0.29
9.3 | transform | 1.0 | 10 | -20 | 1

**Comment by Animator-Anon** [comment]
Yes.

They are handled like this in the code:
   tmp_frame_no = int(float(key_frame_parts[0]) * mysettings['fps'])

The time is converted to a float number and multiplied by the FPS, and finally the integer part extracted to get the frame number.

**Comment by LIQUIDMIND111** [comment]
oh ok, so i just add the 1.4 and 2.5 in the seconds section just like the regular numbers..??
