### ISSUE TITLE
Error on Generation  AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by strouder** [Animator-Anon/Animator#6]
**Describe the bug**
Using the Animator Script "animation.py" gives an error: 

Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\ui.py", line 184, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\stable-diffusion-webui\webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\modules\img2img.py", line 124, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 159, in run
    processed = script.run(p, *script_args)
  File "C:\AI\stable-diffusion-webui\scripts\animation.py", line 294, in run
    initial_color_corrections = [processing.setup_color_correction(p.init_images[0])]
  File "C:\AI\stable-diffusion-webui\modules\processing.py", line 31, in setup_color_correction
    correction_target = cv2.cvtColor(np.asarray(image.copy()), cv2.COLOR_RGB2LAB)
AttributeError: 'NoneType' object has no attribute 'copy'

**To Reproduce**
1. Go to img2img
2. Script: Animator
3 Positive Prompt (Animator Panel): Copper Plate Engraving style. Rosaceae, sharp, gothic, crepuscular rays, light scattering, trending on pinterest
4. Keyframes Textfield: 0 | 0.4 | 2.5 | 0 | 0 | extreme close up a huge boquet of thirteeen black roses in the garden | |

2 | 0.4 | 1 | 00 | 0 | a flock of flying ravens in the forest, | |   

4 | 0.4 | 1 | 00 | 0 | a flock of flying ravens in the forest | |

6 | 0.4 | 1 | 00 | 0 | a big raven with spreaf wings on a tombstone| |

8 | 0.4 | 1 | 00 | 0 | a boquet of black roses in the forest | |

10 | 0.4 | 1 | 00 | 0 | the high detail interior of a gothic cathedral | |

12 | 0.4 | 1 | 00 | 0 | an extreme close up of a bee in a flower bed | |

14 | 0.4 | 1 | 00 | 0 | a flock of flying ravens in the forest | |

5. GENERATE

**Expected behavior**
Should generate images and video

**Screenshots**

![1](https://user-images.githubusercontent.com/21327400/195501638-a3b6ca44-16af-435c-be94-103b6d3514c1.png)
![2](https://user-images.githubusercontent.com/21327400/195501657-7d8fc9d6-7ce7-4deb-9786-b3f21035d4ac.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Commit hash: 698d303b04e293635bfb49c525409f3bcf671dce

**Comment by Animator-Anon** [comment]
Did you load in a picture in img2img? It needs something to work from. Either send one from txt2img, png info or drag one into the window.

**Comment by Animator-Anon** [comment]
[20221013165456.webm](https://user-images.githubusercontent.com/114563845/195525018-4efe527a-81d8-40eb-a984-6c99b5774b96.webm)

**Comment by Animator-Anon** [comment]
![00045-3145869471-cat](https://user-images.githubusercontent.com/114563845/195525213-037f01aa-c474-4441-b0cc-32c3642bd548.png)
Starting picture
