### ISSUE TITLE
[Feature Request] diffusion_cadence

### ISSUE THREAD

**Issue by blackneoo** [Animator-Anon/Animator#7]
First of all Kudos for a very good script, been having lots of fun with it)

My suggestion is to add a diffusion_cadence option similar to Deforum, this would allow for much smoother output by interpolating frames based on the value set in diffusion_cadence

**Comment by Animator-Anon** [comment]
I'll check it out, thanks for suggestion.

**Comment by Animator-Anon** [comment]
I think this will be sorted out by the keyframe interpolation feature another user submitted.
The positive (at this stage) prompts are weighted from one prompt keyframe to the next, giving a smoother transition and a bit more control.
