### ISSUE TITLE
Feature Request: Z Pixel Shift and 3D Animation 

### ISSUE THREAD

**Issue by udside** [Animator-Anon/Animator#9]
Hi,
Firstly, thank you for this great script works nicely!

I'd like second the request for frame-rate/diffusion cadence 

but I would also like the ability to animate along the Z axis as well as in 3D space. 
An implementation of this can be seen in Deforum's Stable Diff. Animator - https://github.com/HelixNGC7293/DeforumStableDiffusionLocal 

Thanks

**Comment by Animator-Anon** [comment]
I'll check it out.

**Comment by Animator-Anon** [comment]
I'm probably too dumb to implement this, but notice this is happening. Might have what you need.
https://github.com/deforum-art/deforum-for-automatic1111-webui
